services:
  - type: web
    name: whatsapp-sender
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: whatsapp-sessions
      mountPath: /tmp/whatsapp-sessions
      sizeGB: 1

